# Generated by Django 5.2.7 on 2025-10-14 01:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cantidad_total', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Inventario')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Accesorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReporteFaltante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_faltante', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unidades faltantes reportadas')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADO', 'Confirmado (Requiere Compra)'), ('DESCARTADO', 'Descartado por Empleado/Admin')], default='PENDIENTE', max_length=20)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesorios.accesorio')),
                ('empleado_confirmacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_confirmados', to=settings.AUTH_USER_MODEL)),
                ('empleado_reporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Faltante',
                'verbose_name_plural': 'Reportes de Faltantes',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
