# Generated by Django 5.2.7 on 2025-10-14 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_comprada', models.PositiveIntegerField(default=0, verbose_name='Cantidad de unidades compradas')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_procesadas', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.OneToOneField(limit_choices_to={'estado': 'CONFIRMADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='reposicion', to='accesorios.reportefaltante')),
            ],
            options={
                'verbose_name': 'Reposición de Stock',
                'verbose_name_plural': 'Reposiciones de Stock',
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
