# Generated by Django 5.2.6 on 2025-10-14 06:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesorios', '0002_reposicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefaltante',
            name='cantidad_faltante',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reposicion',
            name='reporte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reposicion', to='accesorios.reportefaltante'),
        ),
    ]
