# Generated by Django 5.2.7 on 2025-10-19 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesorios', '0003_alter_reportefaltante_cantidad_faltante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesorios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesorio',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesorios_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistorialAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesorio_nombre', models.CharField(max_length=100)),
                ('accesorio_id', models.PositiveIntegerField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('CREADO', 'Accesorio Creado'), ('EDITADO', 'Accesorio Editado'), ('ELIMINADO', 'Accesorio Eliminado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Accesorio',
                'verbose_name_plural': 'Historial de Accesorios',
                'ordering': ['-fecha'],
            },
        ),
    ]
