# Generated by Django 5.2.6 on 2025-10-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesorios', '0004_add_audit_fields_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
