# Generated by Django 5.2.6 on 2025-10-21 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesorios', '0005_accesorio_activo'),
        ('proveedores', '0003_remove_proveedor_direccion_proveedor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesorios', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
    ]
