# Generated by Django 5.2.6 on 2025-10-01 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('BASICO', 'Básico'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duracion_dias', models.IntegerField(default=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('socio', models.OneToOneField(limit_choices_to={'profile__rol': 'Socio'}, on_delete=django.db.models.deletion.CASCADE, related_name='gestion_membresia', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('entrenador', models.ForeignKey(limit_choices_to={'profile__rol__in': ['Entrenador', 'Administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_rutinas_creadas', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(limit_choices_to={'profile__rol': 'Socio'}, on_delete=django.db.models.deletion.CASCADE, related_name='gestion_rutinas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dia_semana', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado')], max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('capacidad', models.IntegerField(default=20)),
                ('entrenador', models.ForeignKey(limit_choices_to={'profile__rol__in': ['Entrenador', 'Administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_clases_impartidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nombre', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
