# Generated by Django 5.2.7 on 2025-10-14 02:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membresia',
            options={'ordering': ['-clases_restantes', '-fecha_inicio'], 'verbose_name': 'Membresía', 'verbose_name_plural': 'Membresías'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['limite_clases', 'precio'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='duracion_dias',
        ),
        migrations.AddField(
            model_name='membresia',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='¿Está Activa?'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='clases_restantes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de clases disponibles para el socio.', verbose_name='Clases Restantes'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='pagada',
            field=models.BooleanField(default=True, verbose_name='¿Membresía Pagada?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='limite_clases',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número total de clases incluidas en este plan (Ej: 12 para 3 veces por semana).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Límite de Clases/Accesos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='gestion.plan'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='socio',
            field=models.ForeignKey(limit_choices_to={'profile__rol': 'Socio'}, on_delete=django.db.models.deletion.CASCADE, related_name='membresias_adquiridas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True, default=1, verbose_name='Descripción y Beneficios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio (ARS)'),
        ),
    ]
