# Generated by Django 5.2.7 on 2025-10-14 17:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_membresia_options_alter_plan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membresia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='clases_restantes',
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='pagada',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='limite_clases',
        ),
        migrations.AddField(
            model_name='membresia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membresia',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2099, 12, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='duracion_dias',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.plan'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='socio',
            field=models.OneToOneField(limit_choices_to={'profile__rol': 'Socio'}, on_delete=django.db.models.deletion.CASCADE, related_name='gestion_membresia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
