# Generated by Django 5.2.6 on 2025-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('Entrenador', 'entrenador'), ('Socio', 'socio')], max_length=20),
        ),
    ]
