# Generated by Django 5.2.7 on 2025-10-13 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('capacidad', models.IntegerField(default=50, verbose_name='Cupos Máximos')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado por Socio'), ('FINALIZADO', 'Finalizado (Asistido)')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno de Gimnasio',
                'verbose_name_plural': 'Turnos de Gimnasio',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
    ]
