# Generated by Django 5.2.7 on 2025-10-13 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_socio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['hora_inicio'], 'verbose_name': 'Turno de Gimnasio', 'verbose_name_plural': 'Turnos de Gimnasio'},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_hora_inicio',
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_fin',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 9, 0), verbose_name='Fecha/Hora de Fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_inicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 9, 0), verbose_name='Fecha/Hora de Inicio'),
            preserve_default=False,
        ),
    ]
