"""
Django settings for gimnasio project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
from datetime import timedelta # Necesario si vas a manejar tokens o sesiones limitadas (opcional)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a!z1qcsuazpo3q9kjmkf$^6!2zd1qcp6^q#c3t@x_nl((f%yl9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# ------------------------------------------------------------------
# Application definition
# ------------------------------------------------------------------

INSTALLED_APPS = [
    # Core Django Apps (Obligatorias)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 3rd Party Apps (Funcionalidad extra)
    'django.contrib.humanize',      
    'widget_tweaks',                

    # Local Apps (Tus módulos de proyecto)
    'cuentas.apps.CuentasConfig',   
    'gestion',                      
    'turnos',                       
    'accesorios',  
    'proveedores',
                     
]

# Configuración de URLs de autenticación
LOGIN_URL = 'login'              # URL para redirigir a usuarios no autenticados
LOGIN_REDIRECT_URL = 'dashboard' # URL a donde ir después de iniciar sesión con éxito
LOGOUT_REDIRECT_URL = 'login'    # URL a donde ir después de cerrar sesión


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ------------------------------------------------------------------
# Configuración de Usuario Personalizado (CRÍTICO)
# ------------------------------------------------------------------

# IMPORTANTE: Debes cambiar 'auth.User' por el nombre de tu modelo de usuario
# personalizado si has extendido AbstractUser.
# Si tu modelo de usuario está en 'cuentas/models.py' y se llama 'CustomUser',
# debe ser: AUTH_USER_MODEL = 'cuentas.CustomUser'
# Si estás usando el modelo User por defecto, puedes comentar esta línea.
# ASUMO que tu modelo se llama 'User' en la app 'cuentas':

# ------------------------------------------------------------------

ROOT_URLCONF = 'gimnasio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Directorio principal de plantillas (e.g., base.html, login.html)
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True, # Busca plantillas dentro de cada app (e.g., turnos/templates/turnos/...)
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth', # Provee el objeto 'user'
                'django.contrib.messages.context_processors.messages', # Provee los mensajes flash

                'cuentas.context_processors.perfil_context', # Procesador para inyectar el objeto 'profile' en todas las plantillas
            ],
        },
    },
]

WSGI_APPLICATION = 'gimnasio.wsgi.application'


# ------------------------------------------------------------------
# Database (PostgreSQL/Supabase)
# ------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.dfplifenjfhgdamtfukb',
        'PASSWORD': 'root',
        'HOST': 'aws-1-us-east-2.pooler.supabase.com', 
        'PORT': '6543',
    }
}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'gimnasio',  
#        'USER': 'root',      
#        'PASSWORD': 'root',  
#        'HOST': 'localhost',  
#        'PORT': '3306',            
#    }
#}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ------------------------------------------------------------------
# Internationalization and Timezone
# ------------------------------------------------------------------

LANGUAGE_CODE = 'es-ar' # Español de Argentina

TIME_ZONE = 'America/Argentina/Buenos_Aires' # Zona horaria de Buenos Aires (aplica a la mayoría de Argentina)

USE_I18N = True # Habilitar traducciones (Internacionalización)

USE_TZ = True # Habilitar soporte para zonas horarias


# ------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# ------------------------------------------------------------------

STATIC_URL = 'static/' # Prefijo de URL para servir archivos estáticos

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static") # Directorio donde Django busca archivos estáticos en desarrollo
]

# Configuración de archivos estáticos para producción (Opcional, pero recomendado para el futuro)
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'