"""
Django settings for gimnasio project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a!z1qcsuazpo3q9kjmkf$^6!2zd1qcp6^q#c3t@x_nl((f%yl9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'cuentas.apps.CuentasConfig',    # App de usuario y Perfiles
    'gestion',                       # App de Planes, Membresias, Rutinas, etc (Ajustar si esta app debe estar aquí)
    'turnos',                        # App para gestionar turnos
]

LOGIN_URL = 'login' 
LOGIN_REDIRECT_URL = 'dashboard'  # a dónde enviar luego de login
LOGOUT_REDIRECT_URL = 'login'     # a dónde enviar luego de logout


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -------------------------------------------------------------
# CORRECCIÓN CLAVE: Asegura que el nombre de tu modelo sea EXACTO.
# Si tu modelo de usuario personalizado en cuentas/models.py se llama 
# 'CustomUser', la línea debe ser: 'cuentas.CustomUser'
# Si se llama 'Socio', debe ser: 'cuentas.Socio'
# Dejamos 'cuentas.User' asumiendo que ese es el nombre de tu modelo.
AUTH_USER_MODEL = 'auth.User'
# -------------------------------------------------------------

ROOT_URLCONF = 'gimnasio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'cuentas.context_processors.perfil_context',  # Agregado para pasar el perfil a todas las plantillas
            ],
        },
    },
]

WSGI_APPLICATION = 'gimnasio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.dfplifenjfhgdamtfukb',
        'PASSWORD': 'root',
        'HOST': 'aws-1-us-east-2.pooler.supabase.com', 
        'PORT': '6543',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar' # Cambiado a español Argentina, común en desarrollo local.

TIME_ZONE = 'America/Argentina/Buenos_Aires' # Cambiado a TZ de Argentina

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'