# Generated by Django 5.2.6 on 2025-10-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
